import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import UserAuth from '@/features/contextApi/userAuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Crack Bot',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      
      <body className={inter.className} ><UserAuth>{children} </UserAuth></body>
    </html>

  )
}
